### ISSUE TITLE
Dicas e feedback

### ISSUE THREAD

**Issue by RenatoCesarF** [LorenzoMichelotti/book-of-made-up-words#1]
Boa tarde, seu projeto apareceu aqui no meu Linkedin, achei muito interessante e fui testar. Vou te dar umas dicas de melhoria aqui, se quiser acho que seria legal adicionar.

- [x] Remover as pas do inicio e final caso a pessoa tenha colocado na descrição, já que você coloca automaticamente no front-end, seria interessante remover caso a pessoa tenha colocado. Isso aconteceu com o teste que eu fiz

- [x] Eu mudaria um pouco a cor do nome da pessoa, por ser azul parece ser um link mas acho que não é. Talve se você deixar um pouco mais claro ou mudar um pouquinho a cor, não cause essa confusão

- [ ] Outra coisa interessante seria adicionar aquele tipo de lazy loading nos cards quando esta carregando, em vez de só mostrar o circulo de loading. Esses cards são bem simples, você pode ver exemplos na netflix e no youtube, isso vai deixar seu site mais rápido em alguns casos e também pode melhorar a performance geral dele na medição de first-painted-content e esse tipo de coisa

São só algumas ideias, então fique a vontade pra fazer ou não qualquer uma delas. 

Abraços. Boa sorte

**Comment by LorenzoMichelotti** [comment]
Primeiramente queria agradecer por tomar seu tempo para escrever um feedback tão detalhado! achei realmente incrível. Sobre as mudanças propostas, achei todos os seus pontos bem interessantes, especialmente o lazy loading, com certeza será um upgrade e tanto quando aplica-lo! 

Em relação as aspas, creio que possa ter retirado um pouco de liberdade dos usuários. Nesse caso menos é mais.

Por fim, sobre o nome do criador, de fato a principio iria ser um link. Ao longo do desenvolvimento optei por remover o sistema de usuário registrados do MVP
e não percebi que a cor azul mesmo sem underline fazia com que o nome parecesse um link... com certeza encontrarei outra solução!

Mais uma vez, agradeço de coração pelo seu feedback! valeu!
